### ISSUE TITLE
Uncaught Error: Invariant Violation: _registerComponent(...)

### ISSUE THREAD

**Issue by vwrobel** [yunluyl/react-redux-mapbox-gl#1]
Hello yunluyl,

After a fresh install of your package, I got the following error in my browser running `npm test`:

> Uncaught Error: Invariant Violation: _registerComponent(...): Target container is not a DOM element.

It seems link to [this SO question](http://stackoverflow.com/questions/26566317/invariant-violation-registercomponent-target-container-is-not-a-dom-elem).

I had to change `test/index/index.pug`:

```
doctype html
html
    head
        script(src='https://api.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.js')
        link(href='https://api.mapbox.com/mapbox-gl-js/v0.20.1/mapbox-gl.css' rel='stylesheet')
        link(href='./globalStyle.css' rel='stylesheet')
    body
        div#root
        -> script(type='text/javascript' src='./bundle.js' defer async)
```

Your package looks great!

**Comment by yunluyl** [comment]
Thanks for reporting this issue. I'll fix this later today. Please let me know if you have any problems. I'm actively maintaining this repo.

**Comment by yunluyl** [comment]
Issue fixed, thanks for your contribution @vwrobel

**Comment by yunluyl** [comment]
I updated the packaging method. Now this module is pre-compiled. You don't need to use Babel to compile this module any more. Thanks for your suggestions @vwrobel !
